import pandas as pd

print("=" * 60)
print("TRAIN.CSV")
print("=" * 60)
train = pd.read_csv("data/Train.csv")
print("Shape:", train.shape)
print("Columns:", list(train.columns))
print(train.head(3))
print()

print("=" * 60)
print("VAL.CSV")
print("=" * 60)
val = pd.read_csv("data/Val.csv")
print("Shape:", val.shape)
print("Columns:", list(val.columns))
print(val.head(3))
print()

print("=" * 60)
print("TEST.CSV")
print("=" * 60)
test = pd.read_csv("data/Test.csv")
print("Shape:", test.shape)
print("Columns:", list(test.columns))
print(test.head(3))
print()

print("=" * 60)
print("SAMPLE SUBMISSION.CSV")
print("=" * 60)
sample = pd.read_csv("data/SampleSubmission.csv")
print("Shape:", sample.shape)
print("Columns:", list(sample.columns))
print(sample.head(3))
print()

if "language" in train.columns:
    print("Languages in Train:", train["language"].unique())
elif "Language" in train.columns:
    print("Languages in Train:", train["Language"].unique())

print()
print("=" * 60)
print("ALL SUBSETS IN TRAIN")
print("=" * 60)
print(train["subset"].value_counts())

print()
print("=" * 60)
print("FULL SAMPLE - INPUT/OUTPUT")
print("=" * 60)
print("INPUT:", train["input"].iloc[0])
print()
print("OUTPUT:", train["output"].iloc[0])
print()
print("INPUT LENGTH (chars):", train["input"].str.len().describe())
print()
print("OUTPUT LENGTH (chars):", train["output"].str.len().describe())